{"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"article","title":"Error Handling"},"primaryContentSections":[{"content":[{"inlineContent":[{"type":"emphasis","inlineContent":[{"text":"Error handling","type":"text"}]},{"text":" is the process of responding to","type":"text"},{"text":" ","type":"text"},{"text":"and recovering from error conditions in your program.","type":"text"},{"text":" ","type":"text"},{"text":"Swift provides first-class support for","type":"text"},{"text":" ","type":"text"},{"text":"throwing, catching, propagating, and manipulating","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"recoverable errors at runtime."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Some operations"},{"type":"text","text":" "},{"type":"text","text":"aren’t guaranteed to always complete execution or produce a useful output."},{"type":"text","text":" "},{"type":"text","text":"Optionals are used to represent the absence of a value,"},{"type":"text","text":" "},{"type":"text","text":"but when an operation fails,"},{"type":"text","text":" "},{"type":"text","text":"it’s often useful to understand what caused the failure,"},{"type":"text","text":" "},{"type":"text","text":"so that your code can respond accordingly."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"As an example, consider the task of reading and processing data from a file on disk."},{"type":"text","text":" "},{"type":"text","text":"There are a number of ways this task can fail, including"},{"type":"text","text":" "},{"type":"text","text":"the file not existing at the specified path,"},{"type":"text","text":" "},{"type":"text","text":"the file not having read permissions, or"},{"type":"text","text":" "},{"type":"text","text":"the file not being encoded in a compatible format."},{"type":"text","text":" "},{"type":"text","text":"Distinguishing among these different situations"},{"type":"text","text":" "},{"type":"text","text":"allows a program to resolve some errors"},{"type":"text","text":" "},{"text":"and to communicate to the user any errors it can’t resolve.","type":"text"}],"type":"paragraph"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error handling in Swift interoperates with error handling patterns"},{"text":" ","type":"text"},{"text":"that use the ","type":"text"},{"type":"codeVoice","code":"NSError"},{"text":" class in Cocoa and Objective-C.","type":"text"},{"text":" ","type":"text"},{"text":"For more information about this class,","type":"text"},{"text":" ","type":"text"},{"text":"see ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift"},{"text":".","type":"text"}]}],"style":"note","type":"aside"},{"text":"Representing and Throwing Errors","level":2,"type":"heading","anchor":"Representing-and-Throwing-Errors"},{"type":"paragraph","inlineContent":[{"text":"In Swift, errors are represented by","type":"text"},{"text":" ","type":"text"},{"text":"values of types that conform to the ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" protocol.","type":"text"},{"text":" ","type":"text"},{"text":"This empty protocol indicates that a type","type":"text"},{"text":" ","type":"text"},{"text":"can be used for error handling.","type":"text"}]},{"inlineContent":[{"text":"Swift enumerations are particularly well suited to modeling","type":"text"},{"text":" ","type":"text"},{"text":"a group of related error conditions,","type":"text"},{"text":" ","type":"text"},{"text":"with associated values allowing for additional information","type":"text"},{"text":" ","type":"text"},{"text":"about the nature of an error to be communicated.","type":"text"},{"text":" ","type":"text"},{"text":"For example, here’s how you might represent the error conditions","type":"text"},{"text":" ","type":"text"},{"text":"of operating a vending machine inside a game:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["enum VendingMachineError: Error {","    case invalidSelection","    case insufficientFunds(coinsNeeded: Int)","    case outOfStock","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Throwing an error lets you indicate that something unexpected happened","type":"text"},{"text":" ","type":"text"},{"text":"and the normal flow of execution can’t continue.","type":"text"},{"text":" ","type":"text"},{"text":"You use a ","type":"text"},{"type":"codeVoice","code":"throw"},{"text":" statement to throw an error.","type":"text"},{"text":" ","type":"text"},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"text":"the following code throws an error to indicate","type":"text"},{"text":" ","type":"text"},{"text":"that five additional coins are needed by the vending machine:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["throw VendingMachineError.insufficientFunds(coinsNeeded: 5)"]},{"anchor":"Handling-Errors","text":"Handling Errors","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When an error is thrown,"},{"text":" ","type":"text"},{"text":"some surrounding piece of code must be responsible","type":"text"},{"text":" ","type":"text"},{"text":"for handling the error —","type":"text"},{"text":" ","type":"text"},{"text":"for example, by correcting the problem,","type":"text"},{"text":" ","type":"text"},{"text":"trying an alternative approach,","type":"text"},{"text":" ","type":"text"},{"text":"or informing the user of the failure.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"There are four ways to handle errors in Swift.","type":"text"},{"text":" ","type":"text"},{"text":"You can propagate the error from a function to the code that calls that function,","type":"text"},{"text":" ","type":"text"},{"text":"handle the error using a ","type":"text"},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" statement,","type":"text"},{"text":" ","type":"text"},{"text":"handle the error as an optional value,","type":"text"},{"text":" ","type":"text"},{"text":"or assert that the error will not occur.","type":"text"},{"text":" ","type":"text"},{"text":"Each approach is described in a section below.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When a function throws an error,"},{"type":"text","text":" "},{"type":"text","text":"it changes the flow of your program,"},{"type":"text","text":" "},{"type":"text","text":"so it’s important that you can quickly identify places in your code that can throw errors."},{"type":"text","text":" "},{"type":"text","text":"To identify these places in your code, write the "},{"type":"codeVoice","code":"try"},{"type":"text","text":" keyword —"},{"type":"text","text":" "},{"type":"text","text":"or the "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" or "},{"type":"codeVoice","code":"try!"},{"type":"text","text":" variation —"},{"type":"text","text":" "},{"type":"text","text":"before a piece of code that calls a function, method, or initializer that can throw an error."},{"type":"text","text":" "},{"type":"text","text":"These keywords are described in the sections below."}]},{"name":"Note","type":"aside","content":[{"inlineContent":[{"text":"Error handling in Swift resembles exception handling in other languages,","type":"text"},{"text":" ","type":"text"},{"text":"with the use of the ","type":"text"},{"type":"codeVoice","code":"try"},{"text":", ","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"throw"},{"text":" keywords.","type":"text"},{"text":" ","type":"text"},{"text":"Unlike exception handling in many languages —","type":"text"},{"text":" ","type":"text"},{"text":"including Objective-C —","type":"text"},{"text":" ","type":"text"},{"text":"error handling in Swift doesn’t involve unwinding the call stack,","type":"text"},{"text":" ","type":"text"},{"text":"a process that can be computationally expensive.","type":"text"},{"text":" ","type":"text"},{"text":"As such, the performance characteristics","type":"text"},{"text":" ","type":"text"},{"text":"of a ","type":"text"},{"type":"codeVoice","code":"throw"},{"text":" statement","type":"text"},{"text":" ","type":"text"},{"text":"are comparable to those of a ","type":"text"},{"type":"codeVoice","code":"return"},{"text":" statement.","type":"text"}],"type":"paragraph"}],"style":"note"},{"text":"Propagating Errors Using Throwing Functions","type":"heading","level":3,"anchor":"Propagating-Errors-Using-Throwing-Functions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To indicate that a function, method, or initializer can throw an error,"},{"type":"text","text":" "},{"type":"text","text":"you write the "},{"type":"codeVoice","code":"throws"},{"type":"text","text":" keyword in the function’s declaration"},{"type":"text","text":" "},{"type":"text","text":"after its parameters."},{"type":"text","text":" "},{"type":"text","text":"A function marked with "},{"type":"codeVoice","code":"throws"},{"type":"text","text":" is called a "},{"type":"emphasis","inlineContent":[{"type":"text","text":"throwing function"}]},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the function specifies a return type,"},{"type":"text","text":" "},{"type":"text","text":"you write the "},{"type":"codeVoice","code":"throws"},{"type":"text","text":" keyword before the return arrow ("},{"type":"codeVoice","code":"->"},{"type":"text","text":")."}]},{"type":"codeListing","syntax":"swift","code":["func canThrowErrors() throws -> String","","func cannotThrowErrors() -> String"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A throwing function propagates errors that are thrown inside of it"},{"type":"text","text":" "},{"type":"text","text":"to the scope from which it’s called."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Only throwing functions can propagate errors."},{"type":"text","text":" "},{"type":"text","text":"Any errors thrown inside a nonthrowing function"},{"type":"text","text":" "},{"type":"text","text":"must be handled inside the function."}]}],"style":"note","type":"aside","name":"Note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the example below,"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"VendingMachine"},{"type":"text","text":" class has a "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"type":"text","text":"that throws an appropriate "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" "},{"type":"text","text":"if the requested item isn’t available,"},{"type":"text","text":" "},{"type":"text","text":"is out of stock,"},{"type":"text","text":" "},{"type":"text","text":"or has a cost that exceeds the current deposited amount:"}]},{"code":["struct Item {","    var price: Int","    var count: Int","}","","class VendingMachine {","    var inventory = [","        \"Candy Bar\": Item(price: 12, count: 7),","        \"Chips\": Item(price: 10, count: 4),","        \"Pretzels\": Item(price: 7, count: 11)","    ]","    var coinsDeposited = 0","","    func vend(itemNamed name: String) throws {","        guard let item = inventory[name] else {","            throw VendingMachineError.invalidSelection","        }","","        guard item.count > 0 else {","            throw VendingMachineError.outOfStock","        }","","        guard item.price <= coinsDeposited else {","            throw VendingMachineError.insufficientFunds(coinsNeeded: item.price - coinsDeposited)","        }","","        coinsDeposited -= item.price","","        var newItem = item","        newItem.count -= 1","        inventory[name] = newItem","","        print(\"Dispensing \\(name)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The implementation of the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"type":"text","text":"uses "},{"type":"codeVoice","code":"guard"},{"type":"text","text":" statements to exit the method early and throw appropriate errors"},{"type":"text","text":" "},{"type":"text","text":"if any of the requirements for purchasing a snack aren’t met."},{"type":"text","text":" "},{"text":"Because a ","type":"text"},{"code":"throw","type":"codeVoice"},{"text":" statement immediately transfers program control,","type":"text"},{"text":" ","type":"text"},{"text":"an item will be vended only if all of these requirements are met.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Because the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method propagates any errors it throws,"},{"type":"text","text":" "},{"type":"text","text":"any code that calls this method must either handle the errors —"},{"type":"text","text":" "},{"type":"text","text":"using a "},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement, "},{"type":"codeVoice","code":"try?"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"try!"},{"text":" —","type":"text"},{"text":" ","type":"text"},{"text":"or continue to propagate them.","type":"text"},{"text":" ","type":"text"},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" in the example below"},{"type":"text","text":" "},{"type":"text","text":"is also a throwing function,"},{"type":"text","text":" "},{"type":"text","text":"and any errors that the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method throws will"},{"type":"text","text":" "},{"type":"text","text":"propagate up to the point where the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" function is called."}]},{"code":["let favoriteSnacks = [","    \"Alice\": \"Chips\",","    \"Bob\": \"Licorice\",","    \"Eve\": \"Pretzels\",","]","func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {","    let snackName = favoriteSnacks[person] ?? \"Candy Bar\"","    try vendingMachine.vend(itemNamed: snackName)","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In this example,"},{"type":"text","text":" "},{"type":"text","text":"the "},{"code":"buyFavoriteSnack(person: vendingMachine:)","type":"codeVoice"},{"type":"text","text":" function looks up a given person’s favorite snack"},{"type":"text","text":" "},{"type":"text","text":"and tries to buy it for them by calling the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method."},{"type":"text","text":" "},{"type":"text","text":"Because the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method can throw an error,"},{"type":"text","text":" "},{"type":"text","text":"it’s called with the "},{"type":"codeVoice","code":"try"},{"type":"text","text":" keyword in front of it."}]},{"inlineContent":[{"text":"Throwing initializers can propagate errors in the same way as throwing functions.","type":"text"},{"text":" ","type":"text"},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the initializer for the "},{"type":"codeVoice","code":"PurchasedSnack"},{"type":"text","text":" structure in the listing below"},{"type":"text","text":" "},{"type":"text","text":"calls a throwing function as part of the initialization process,"},{"type":"text","text":" "},{"type":"text","text":"and it handles any errors that it encounters by propagating them to its caller."}],"type":"paragraph"},{"syntax":"swift","code":["struct PurchasedSnack {","    let name: String","    init(name: String, vendingMachine: VendingMachine) throws {","        try vendingMachine.vend(itemNamed: name)","        self.name = name","    }","}"],"type":"codeListing"},{"level":3,"anchor":"Handling-Errors-Using-Do-Catch","type":"heading","text":"Handling Errors Using Do-Catch"},{"inlineContent":[{"text":"You use a ","type":"text"},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" statement to handle errors","type":"text"},{"text":" ","type":"text"},{"text":"by running a block of code.","type":"text"},{"text":" ","type":"text"},{"text":"If an error is thrown by the code in the ","type":"text"},{"type":"codeVoice","code":"do"},{"text":" clause,","type":"text"},{"text":" ","type":"text"},{"text":"it’s matched against the ","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" clauses","type":"text"},{"text":" ","type":"text"},{"text":"to determine which one of them can handle the error.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Here is the general form of a "},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement:"}],"type":"paragraph"},{"syntax":"swift","code":["do {","    try <#expression#>","    <#statements#>","} catch <#pattern 1#> {","    <#statements#>","} catch <#pattern 2#> where <#condition#> {","    <#statements#>","} catch <#pattern 3#>, <#pattern 4#> where <#condition#> {","    <#statements#>","} catch {","    <#statements#>","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"You write a pattern after "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" to indicate what errors"},{"type":"text","text":" "},{"type":"text","text":"that clause can handle."},{"type":"text","text":" "},{"type":"text","text":"If a "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clause doesn’t have a pattern,"},{"type":"text","text":" "},{"type":"text","text":"the clause matches any error"},{"type":"text","text":" "},{"type":"text","text":"and binds the error to a local constant named "},{"code":"error","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"For more information about pattern matching,"},{"type":"text","text":" "},{"type":"text","text":"see "},{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For example, the following code matches against all three cases"},{"type":"text","text":" "},{"type":"text","text":"of the "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" enumeration."}],"type":"paragraph"},{"syntax":"swift","code":["var vendingMachine = VendingMachine()","vendingMachine.coinsDeposited = 8","do {","    try buyFavoriteSnack(person: \"Alice\", vendingMachine: vendingMachine)","    print(\"Success! Yum.\")","} catch VendingMachineError.invalidSelection {","    print(\"Invalid Selection.\")","} catch VendingMachineError.outOfStock {","    print(\"Out of Stock.\")","} catch VendingMachineError.insufficientFunds(let coinsNeeded) {","    print(\"Insufficient funds. Please insert an additional \\(coinsNeeded) coins.\")","} catch {","    print(\"Unexpected error: \\(error).\")","}","\/\/ Prints \"Insufficient funds. Please insert an additional 2 coins.\""],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"In the above example,"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" function is called in a "},{"type":"codeVoice","code":"try"},{"type":"text","text":" expression,"},{"type":"text","text":" "},{"type":"text","text":"because it can throw an error."},{"type":"text","text":" "},{"type":"text","text":"If an error is thrown,"},{"type":"text","text":" "},{"type":"text","text":"execution immediately transfers to the "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clauses,"},{"type":"text","text":" "},{"type":"text","text":"which decide whether to allow propagation to continue."},{"type":"text","text":" "},{"type":"text","text":"If no pattern is matched, the error gets caught by the final "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" "},{"type":"text","text":"clause and is bound to a local "},{"type":"codeVoice","code":"error"},{"type":"text","text":" constant."},{"type":"text","text":" "},{"type":"text","text":"If no error is thrown,"},{"type":"text","text":" "},{"type":"text","text":"the remaining statements in the "},{"type":"codeVoice","code":"do"},{"type":"text","text":" statement are executed."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clauses don’t have to handle every possible error"},{"type":"text","text":" "},{"type":"text","text":"that the code in the "},{"code":"do","type":"codeVoice"},{"type":"text","text":" clause can throw."},{"type":"text","text":" "},{"type":"text","text":"If none of the "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clauses handle the error,"},{"type":"text","text":" "},{"type":"text","text":"the error propagates to the surrounding scope."},{"type":"text","text":" "},{"type":"text","text":"However, the propagated error"},{"type":"text","text":" "},{"type":"text","text":"must be handled by "},{"type":"emphasis","inlineContent":[{"type":"text","text":"some"}]},{"type":"text","text":" surrounding scope."},{"type":"text","text":" "},{"type":"text","text":"In a nonthrowing function,"},{"type":"text","text":" "},{"type":"text","text":"an enclosing "},{"code":"do","type":"codeVoice"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"must handle the error."},{"type":"text","text":" "},{"type":"text","text":"In a throwing function,"},{"type":"text","text":" "},{"type":"text","text":"either an enclosing "},{"code":"do","type":"codeVoice"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"or the caller"},{"type":"text","text":" "},{"type":"text","text":"must handle the error."},{"type":"text","text":" "},{"type":"text","text":"If the error propagates to the top-level scope"},{"type":"text","text":" "},{"type":"text","text":"without being handled,"},{"type":"text","text":" "},{"type":"text","text":"you’ll get a runtime error."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"For example, the above example can be written so any","type":"text"},{"text":" ","type":"text"},{"text":"error that isn’t a ","type":"text"},{"code":"VendingMachineError","type":"codeVoice"},{"text":" is instead","type":"text"},{"text":" ","type":"text"},{"text":"caught by the calling function:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func nourish(with item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch is VendingMachineError {","        print(\"Couldn't buy that from the vending machine.\")","    }","}","","do {","    try nourish(with: \"Beet-Flavored Chips\")","} catch {","    print(\"Unexpected non-vending-machine-related error: \\(error)\")","}","\/\/ Prints \"Couldn't buy that from the vending machine.\""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the "},{"type":"codeVoice","code":"nourish(with:)"},{"type":"text","text":" function,"},{"type":"text","text":" "},{"type":"text","text":"if "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" throws an error that’s"},{"type":"text","text":" "},{"type":"text","text":"one of the cases of the "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" enumeration,"},{"type":"text","text":" "},{"type":"codeVoice","code":"nourish(with:)"},{"type":"text","text":" handles the error by printing a message."},{"type":"text","text":" "},{"type":"text","text":"Otherwise,"},{"type":"text","text":" "},{"type":"codeVoice","code":"nourish(with:)"},{"type":"text","text":" propagates the error to its call site."},{"type":"text","text":" "},{"type":"text","text":"The error is then caught by the general "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clause."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Another way to catch several related errors"},{"type":"text","text":" "},{"type":"text","text":"is to list them after "},{"type":"codeVoice","code":"catch"},{"type":"text","text":", separated by commas."},{"type":"text","text":" "},{"type":"text","text":"For example:"}]},{"type":"codeListing","syntax":"swift","code":["func eat(item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch VendingMachineError.invalidSelection, VendingMachineError.insufficientFunds, VendingMachineError.outOfStock {","        print(\"Invalid selection, out of stock, or not enough money.\")","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"eat(item:)"},{"type":"text","text":" function lists the vending machine errors to catch,"},{"type":"text","text":" "},{"type":"text","text":"and its error text corresponds to the items in that list."},{"type":"text","text":" "},{"type":"text","text":"If any of the three listed errors are thrown,"},{"type":"text","text":" "},{"type":"text","text":"this "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clause handles them by printing a message."},{"type":"text","text":" "},{"type":"text","text":"Any other errors are propagated to the surrounding scope,"},{"type":"text","text":" "},{"type":"text","text":"including any vending-machine errors that might be added later."}]},{"type":"heading","level":3,"text":"Converting Errors to Optional Values","anchor":"Converting-Errors-to-Optional-Values"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" to handle an error by converting it to an optional value."},{"type":"text","text":" "},{"type":"text","text":"If an error is thrown while evaluating the "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" expression,"},{"type":"text","text":" "},{"type":"text","text":"the value of the expression is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"in the following code "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" have the same value and behavior:"}]},{"type":"codeListing","syntax":"swift","code":["func someThrowingFunction() throws -> Int {","    \/\/ ...","}","","let x = try? someThrowingFunction()","","let y: Int?","do {","    y = try someThrowingFunction()","} catch {","    y = nil","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"someThrowingFunction()"},{"type":"text","text":" throws an error,"},{"type":"text","text":" "},{"type":"text","text":"the value of "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the value of "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" is the value that the function returned."},{"type":"text","text":" "},{"type":"text","text":"Note that "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" are an optional of whatever type "},{"type":"codeVoice","code":"someThrowingFunction()"},{"type":"text","text":" returns."},{"type":"text","text":" "},{"type":"text","text":"Here the function returns an integer, so "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" are optional integers."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" lets you write concise error handling code"},{"type":"text","text":" "},{"type":"text","text":"when you want to handle all errors in the same way."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"the following code"},{"type":"text","text":" "},{"type":"text","text":"uses several approaches to fetch data,"},{"type":"text","text":" "},{"type":"text","text":"or returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if all of the approaches fail."}]},{"type":"codeListing","syntax":"swift","code":["func fetchData() -> Data? {","    if let data = try? fetchDataFromDisk() { return data }","    if let data = try? fetchDataFromServer() { return data }","    return nil","}"]},{"type":"heading","level":3,"text":"Disabling Error Propagation","anchor":"Disabling-Error-Propagation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Sometimes you know a throwing function or method"},{"type":"text","text":" "},{"type":"text","text":"won’t, in fact, throw an error at runtime."},{"type":"text","text":" "},{"type":"text","text":"On those occasions,"},{"type":"text","text":" "},{"type":"text","text":"you can write "},{"type":"codeVoice","code":"try!"},{"type":"text","text":" before the expression to disable error propagation"},{"type":"text","text":" "},{"type":"text","text":"and wrap the call in a runtime assertion that no error will be thrown."},{"type":"text","text":" "},{"type":"text","text":"If an error actually is thrown, you’ll get a runtime error."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, the following code uses a "},{"type":"codeVoice","code":"loadImage(atPath:)"},{"type":"text","text":" function,"},{"type":"text","text":" "},{"type":"text","text":"which loads the image resource at a given path"},{"type":"text","text":" "},{"type":"text","text":"or throws an error if the image can’t be loaded."},{"type":"text","text":" "},{"type":"text","text":"In this case, because the image is shipped with the application,"},{"type":"text","text":" "},{"type":"text","text":"no error will be thrown at runtime,"},{"text":" ","type":"text"},{"text":"so it’s appropriate to disable error propagation.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let photo = try! loadImage(atPath: \".\/Resources\/John Appleseed.jpg\")"]},{"type":"heading","level":2,"text":"Specifying the Error Type","anchor":"Specifying-the-Error-Type"},{"type":"paragraph","inlineContent":[{"text":"All of the examples above use the most common kind of error handling,","type":"text"},{"text":" ","type":"text"},{"text":"where the errors that your code throws","type":"text"},{"text":" ","type":"text"},{"text":"can be values of any type that conforms to the ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" protocol.","type":"text"},{"text":" ","type":"text"},{"text":"This approach matches the reality that","type":"text"},{"text":" ","type":"text"},{"text":"you don’t know ahead of time every error that could happen","type":"text"},{"text":" ","type":"text"},{"text":"while the code is running,","type":"text"},{"text":" ","type":"text"},{"text":"especially when propagating errors thrown somewhere else.","type":"text"},{"text":" ","type":"text"},{"text":"It also reflects the fact that errors can change over time.","type":"text"},{"text":" ","type":"text"},{"text":"New versions of a library —","type":"text"},{"text":" ","type":"text"},{"text":"including libraries that your dependencies use —","type":"text"},{"text":" ","type":"text"},{"text":"can throw new errors,","type":"text"},{"text":" ","type":"text"},{"text":"and the rich complexity of real-world user configurations","type":"text"},{"text":" ","type":"text"},{"text":"can expose failure modes that weren’t visible during development or testing.","type":"text"},{"text":" ","type":"text"},{"text":"The error handling code in the examples above","type":"text"},{"text":" ","type":"text"},{"text":"always includes a default case to handle errors","type":"text"},{"text":" ","type":"text"},{"text":"that don’t have a specific ","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" clause.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Most Swift code doesn’t specify the type for the errors it throws."},{"type":"text","text":" "},{"type":"text","text":"However,"},{"type":"text","text":" "},{"type":"text","text":"you might limit code to throwing errors of only one specific type"},{"type":"text","text":" "},{"type":"text","text":"in the following special cases:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When running code on an embedded system"},{"type":"text","text":" "},{"type":"text","text":"that doesn’t support dynamic allocation of memory."},{"type":"text","text":" "},{"type":"text","text":"Throwing an instance of "},{"type":"codeVoice","code":"any Error"},{"type":"text","text":" or another boxed protocol type"},{"type":"text","text":" "},{"type":"text","text":"requires allocating memory at runtime to store the error."},{"type":"text","text":" "},{"type":"text","text":"In contrast,"},{"type":"text","text":" "},{"type":"text","text":"throwing an error of a specific type"},{"type":"text","text":" "},{"type":"text","text":"lets Swift avoid heap allocation for errors."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"When the errors are an implementation detail of some unit of code,","type":"text"},{"text":" ","type":"text"},{"text":"like a library,","type":"text"},{"text":" ","type":"text"},{"text":"and aren’t part of the interface to that code.","type":"text"},{"text":" ","type":"text"},{"text":"Because the errors come from only the library,","type":"text"},{"text":" ","type":"text"},{"text":"and not from other dependencies or the library’s clients,","type":"text"},{"text":" ","type":"text"},{"text":"you can make an exhaustive list of all possible failures.","type":"text"},{"text":" ","type":"text"},{"text":"And because these errors are an implementation detail of the library,","type":"text"},{"text":" ","type":"text"},{"text":"they’re always handled within that library.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In code that only propagates errors described by generic parameters,"},{"type":"text","text":" "},{"type":"text","text":"like a function that takes a closure argument"},{"type":"text","text":" "},{"type":"text","text":"and propagates any errors from that closure."},{"type":"text","text":" "},{"type":"text","text":"For a comparison between propagating a specific error type"},{"type":"text","text":" "},{"type":"text","text":"and using "},{"code":"rethrows","type":"codeVoice"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"see "},{"type":"reference","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Declarations#Rethrowing-Functions-and-Methods","isActive":true},{"type":"text","text":"."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"consider code that summarizes ratings"},{"type":"text","text":" "},{"type":"text","text":"and uses the following error type:"}]},{"type":"codeListing","syntax":"swift","code":["enum StatisticsError: Error {","    case noRatings","    case invalidRating(Int)","}"]},{"type":"paragraph","inlineContent":[{"text":"To specify that a function throws only ","type":"text"},{"code":"StatisticsError","type":"codeVoice"},{"text":" values as its errors,","type":"text"},{"text":" ","type":"text"},{"text":"you write ","type":"text"},{"code":"throws(StatisticsError)","type":"codeVoice"},{"text":" instead of only ","type":"text"},{"code":"throws","type":"codeVoice"},{"text":" ","type":"text"},{"text":"when declaring the function.","type":"text"},{"text":" ","type":"text"},{"text":"This syntax is also called ","type":"text"},{"inlineContent":[{"type":"text","text":"typed throws"}],"type":"emphasis"},{"text":" ","type":"text"},{"text":"because you write the error type after ","type":"text"},{"code":"throws","type":"codeVoice"},{"text":" in the declaration.","type":"text"},{"text":" ","type":"text"},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"text":"the function below throws ","type":"text"},{"code":"StatisticsError","type":"codeVoice"},{"text":" values as its errors.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func summarize(_ ratings: [Int]) throws(StatisticsError) {","    guard !ratings.isEmpty else { throw .noRatings }","","    var counts = [1: 0, 2: 0, 3: 0]","    for rating in ratings {","        guard rating > 0 && rating <= 3 else { throw .invalidRating(rating) }","        counts[rating]! += 1","    }","","    print(\"*\", counts[1]!, \"-- **\", counts[2]!, \"-- ***\", counts[3]!)","}"]},{"type":"paragraph","inlineContent":[{"text":"In the code above,","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"type":"codeVoice","code":"summarize(_:)"},{"text":" function summarizes a list of ratings","type":"text"},{"text":" ","type":"text"},{"text":"expressed on a scale of 1 to 3.","type":"text"},{"text":" ","type":"text"},{"text":"This function throws an instance of ","type":"text"},{"type":"codeVoice","code":"StatisticsError"},{"text":" if the input isn’t valid.","type":"text"},{"text":" ","type":"text"},{"text":"Both places in the code above that throw an error","type":"text"},{"text":" ","type":"text"},{"text":"omit the type of the error","type":"text"},{"text":" ","type":"text"},{"text":"because the function’s error type is already defined.","type":"text"},{"text":" ","type":"text"},{"text":"You can use the short form, ","type":"text"},{"type":"codeVoice","code":"throw .noRatings"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"instead of writing ","type":"text"},{"type":"codeVoice","code":"throw StatisticsError.noRatings"},{"text":" ","type":"text"},{"text":"when throwing an error in a function like this.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you write a specific error type at the start of the function,"},{"type":"text","text":" "},{"type":"text","text":"Swift checks that you don’t throw any other errors."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"if you tried to use "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" from examples earlier in this chapter"},{"type":"text","text":" "},{"type":"text","text":"in the "},{"type":"codeVoice","code":"summarize(_:)"},{"type":"text","text":" function above,"},{"type":"text","text":" "},{"type":"text","text":"that code would produce an error at compile time."}]},{"type":"paragraph","inlineContent":[{"text":"You can call a function that uses typed throws","type":"text"},{"text":" ","type":"text"},{"text":"from within a regular throwing function:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func someThrowingFunction() throws {","    let ratings = [1, 2, 3, 2, 2, 1]","    try summarize(ratings)","}"]},{"type":"paragraph","inlineContent":[{"text":"The code above doesn’t specify an error type for ","type":"text"},{"code":"someThrowingFunction()","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"so it throws ","type":"text"},{"code":"any Error","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You could also write the error type explicitly as ","type":"text"},{"code":"throws(any Error)","type":"codeVoice"},{"text":";","type":"text"},{"text":" ","type":"text"},{"text":"the code below is equivalent to the code above:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func someThrowingFunction() throws(any Error) {","    let ratings = [1, 2, 3, 2, 2, 1]","    try summarize(ratings)","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In this code,"},{"type":"text","text":" "},{"type":"codeVoice","code":"someThrowingFunction()"},{"type":"text","text":" propagates any errors that "},{"type":"codeVoice","code":"summarize(_:)"},{"type":"text","text":" throws."},{"type":"text","text":" "},{"type":"text","text":"The errors from "},{"type":"codeVoice","code":"summarize(_:)"},{"type":"text","text":" are always "},{"type":"codeVoice","code":"StatisticsError"},{"type":"text","text":" values,"},{"type":"text","text":" "},{"type":"text","text":"which is also a valid error for "},{"type":"codeVoice","code":"someThrowingFunction()"},{"type":"text","text":" to throw."}]},{"type":"paragraph","inlineContent":[{"text":"Just like you can write a function that never returns","type":"text"},{"text":" ","type":"text"},{"text":"with a return type of ","type":"text"},{"code":"Never","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"you can write a function that never throws with ","type":"text"},{"code":"throws(Never)","type":"codeVoice"},{"text":":","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func nonThrowingFunction() throws(Never) {","  \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"text":"This function can’t throw because","type":"text"},{"text":" ","type":"text"},{"text":"it’s impossible to create a value of type ","type":"text"},{"code":"Never","type":"codeVoice"},{"text":" to throw.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"In addition to specifying a function’s error type,","type":"text"},{"text":" ","type":"text"},{"text":"you can also write a specific error type for a ","type":"text"},{"code":"do","type":"codeVoice"},{"text":"-","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" statement.","type":"text"},{"text":" ","type":"text"},{"text":"For example:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let ratings = []","do throws(StatisticsError) {","    try summarize(ratings)","} catch {","    switch error {","    case .noRatings:","        print(\"No ratings available\")","    case .invalidRating(let rating):","        print(\"Invalid rating: \\(rating)\")","    }","}","\/\/ Prints \"No ratings available\""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In this code,"},{"type":"text","text":" "},{"type":"text","text":"writing "},{"type":"codeVoice","code":"do throws(StatisticsError)"},{"type":"text","text":" indicates that"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement throws "},{"type":"codeVoice","code":"StatisticsError"},{"type":"text","text":" values as its errors."},{"type":"text","text":" "},{"type":"text","text":"Like other "},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statements,"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" clause can either handle every possible error","type":"text"},{"text":" ","type":"text"},{"text":"or propagate unhandled errors for some surrounding scope to handle.","type":"text"},{"text":" ","type":"text"},{"text":"This code handles all of the errors,","type":"text"},{"text":" ","type":"text"},{"text":"using a ","type":"text"},{"code":"switch","type":"codeVoice"},{"text":" statement with one case for each enumeration value.","type":"text"},{"text":" ","type":"text"},{"text":"Like other ","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" clauses that don’t have a pattern,","type":"text"},{"text":" ","type":"text"},{"text":"the clause matches any error","type":"text"},{"text":" ","type":"text"},{"text":"and binds the error to a local constant named ","type":"text"},{"code":"error","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Because the "},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" statement throws ","type":"text"},{"code":"StatisticsError","type":"codeVoice"},{"text":" values,","type":"text"},{"text":" ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" is a value of type ","type":"text"},{"code":"StatisticsError","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" clause above uses a ","type":"text"},{"code":"switch","type":"codeVoice"},{"text":" statement","type":"text"},{"text":" ","type":"text"},{"text":"to match and handle each possible error.","type":"text"},{"text":" ","type":"text"},{"text":"If you tried to add a new case to ","type":"text"},{"code":"StatisticsError","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"without updating the error-handling code,"},{"type":"text","text":" "},{"type":"text","text":"Swift would give you an error"},{"type":"text","text":" "},{"type":"text","text":"because the "},{"type":"codeVoice","code":"switch"},{"type":"text","text":" statement wouldn’t be exhaustive anymore."},{"type":"text","text":" "},{"type":"text","text":"For a library that catches all of its own errors,"},{"type":"text","text":" "},{"text":"you could use this approach to ensure any new errors","type":"text"},{"text":" ","type":"text"},{"text":"get corresponding new code to handle them.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If a function or "},{"type":"codeVoice","code":"do"},{"text":" block throws errors of only a single type,","type":"text"},{"text":" ","type":"text"},{"text":"Swift infers that this code is using typed throws.","type":"text"},{"text":" ","type":"text"},{"text":"Using this shorter syntax,","type":"text"},{"text":" ","type":"text"},{"text":"you could write the ","type":"text"},{"code":"do","type":"codeVoice"},{"text":"-","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" example above as follows:","type":"text"}]},{"code":["let ratings = []","do {","    try summarize(ratings)","} catch {","    switch error {","    case .noRatings:","        print(\"No ratings available\")","    case .invalidRating(let rating):","        print(\"Invalid rating: \\(rating)\")","    }","}","\/\/ Prints \"No ratings available\""],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Even though the ","type":"text"},{"code":"do","type":"codeVoice"},{"text":"-","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" block above","type":"text"},{"text":" ","type":"text"},{"text":"doesn’t specify what type of error it throws,","type":"text"},{"text":" ","type":"text"},{"text":"Swift infers that it throws ","type":"text"},{"code":"StatisticsError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You can explicitly write ","type":"text"},{"code":"throws(any Error)","type":"codeVoice"},{"text":" ","type":"text"},{"text":"to avoid letting Swift infer typed throws.","type":"text"}]},{"anchor":"Specifying-Cleanup-Actions","type":"heading","level":2,"text":"Specifying Cleanup Actions"},{"inlineContent":[{"type":"text","text":"You use a "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement to execute a set of statements"},{"type":"text","text":" "},{"type":"text","text":"just before code execution leaves the current block of code."},{"type":"text","text":" "},{"type":"text","text":"This statement lets you do any necessary cleanup"},{"type":"text","text":" "},{"type":"text","text":"that should be performed regardless"},{"type":"text","text":" "},{"type":"text","text":"of "},{"type":"emphasis","inlineContent":[{"text":"how","type":"text"}]},{"type":"text","text":" execution leaves the current block of code —"},{"type":"text","text":" "},{"type":"text","text":"whether it leaves because an error was thrown"},{"type":"text","text":" "},{"type":"text","text":"or because of a statement such as "},{"code":"return","type":"codeVoice"},{"type":"text","text":" or "},{"code":"break","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"For example, you can use a "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"to ensure that file descriptors are closed"},{"type":"text","text":" "},{"type":"text","text":"and manually allocated memory is freed."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"A "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement defers execution until the current scope is exited."},{"type":"text","text":" "},{"type":"text","text":"This statement consists of the "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" keyword and the statements to be executed later."},{"type":"text","text":" "},{"type":"text","text":"The deferred statements may not contain any code"},{"type":"text","text":" "},{"type":"text","text":"that would transfer control out of the statements,"},{"type":"text","text":" "},{"type":"text","text":"such as a "},{"code":"break","type":"codeVoice"},{"type":"text","text":" or a "},{"code":"return","type":"codeVoice"},{"type":"text","text":" statement,"},{"type":"text","text":" "},{"type":"text","text":"or by throwing an error."},{"type":"text","text":" "},{"type":"text","text":"Deferred actions are executed in the reverse of"},{"type":"text","text":" "},{"type":"text","text":"the order that they’re written in your source code."},{"type":"text","text":" "},{"type":"text","text":"That is, the code in the first "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement executes last,"},{"type":"text","text":" "},{"type":"text","text":"the code in the second "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement executes second to last,"},{"type":"text","text":" "},{"type":"text","text":"and so on."},{"type":"text","text":" "},{"type":"text","text":"The last "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement in source code order executes first."}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func processFile(filename: String) throws {","    if exists(filename) {","        let file = open(filename)","        defer {","            close(file)","        }","        while let line = try file.readline() {","            \/\/ Work with the file.","        }","        \/\/ close(file) is called here, at the end of the scope.","    }","}"]},{"inlineContent":[{"type":"text","text":"The above example uses a "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"to ensure that the "},{"code":"open(_:)","type":"codeVoice"},{"type":"text","text":" function"},{"type":"text","text":" "},{"type":"text","text":"has a corresponding call to "},{"code":"close(_:)","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"You can use a ","type":"text"},{"type":"codeVoice","code":"defer"},{"text":" statement","type":"text"},{"text":" ","type":"text"},{"text":"even when no error handling code is involved.","type":"text"},{"text":" ","type":"text"},{"text":"For more information,","type":"text"},{"text":" ","type":"text"},{"text":"see ","type":"text"},{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ControlFlow#Deferred-Actions","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"name":"Beta Software","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""}]},{"type":"paragraph","inlineContent":[{"text":"This documentation contains preliminary information about an API or technology in development. This information is subject to change, and software implemented according to this documentation should be tested with final operating system software.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Learn more about using ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/support\/beta-software\/","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language"]]},"identifier":{"url":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ErrorHandling","interfaceLanguage":"swift"},"abstract":[{"text":"Respond to and recover from errors.","type":"text"}],"sections":[],"references":{"https://developer.apple.com/documentation/swift/cocoa_design_patterns/handling_cocoa_errors_in_swift":{"title":"Handling Cocoa Errors in Swift","type":"link","titleInlineContent":[{"type":"text","text":"Handling Cocoa Errors in Swift"}],"url":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift"},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/Declarations#Rethrowing-Functions-and-Methods":{"url":"\/documentation\/the-swift-programming-language\/declarations#Rethrowing-Functions-and-Methods","abstract":[],"type":"topic","kind":"section","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Declarations#Rethrowing-Functions-and-Methods","title":"Rethrowing Functions and Methods"},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/Patterns":{"url":"\/documentation\/the-swift-programming-language\/patterns","title":"Patterns","type":"topic","role":"article","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","abstract":[{"type":"text","text":"Match and destructure values."}],"kind":"article"},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language":{"url":"\/documentation\/the-swift-programming-language","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language","role":"collection","title":"The Swift Programming Language (6.2)"},"https://developer.apple.com/support/beta-software/":{"title":"Apple’s beta software","identifier":"https:\/\/developer.apple.com\/support\/beta-software\/","url":"https:\/\/developer.apple.com\/support\/beta-software\/","type":"link","titleInlineContent":[{"text":"Apple’s beta software","type":"text"}]},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/ControlFlow#Deferred-Actions":{"url":"\/documentation\/the-swift-programming-language\/controlflow#Deferred-Actions","abstract":[],"type":"topic","kind":"section","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ControlFlow#Deferred-Actions","title":"Deferred Actions"}}}